from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                """
                ALTER TABLE orders
                ADD COLUMN IF NOT EXISTS promo_code varchar(64) NOT NULL DEFAULT '';
                """,
                """
                CREATE TABLE IF NOT EXISTS promo_codes (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    code varchar(64) NOT NULL UNIQUE,
                    customer_id integer NOT NULL,
                    percentage numeric(5, 2) NOT NULL,
                    max_discount_amount numeric(12, 2) NOT NULL,
                    status varchar(16) NOT NULL DEFAULT 'UNUSED',
                    valid_from timestamp with time zone NULL,
                    valid_to timestamp with time zone NULL,
                    applied_order_id integer NULL,
                    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
                """,
                """
                CREATE TABLE IF NOT EXISTS saga_logs (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    order_id integer NOT NULL,
                    step varchar(64) NOT NULL,
                    status varchar(32) NOT NULL,
                    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
                    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
                """,
                """
                CREATE INDEX IF NOT EXISTS promo_customer_status_idx
                ON promo_codes (customer_id, status);
                """,
                """
                CREATE INDEX IF NOT EXISTS promo_code_customer_idx
                ON promo_codes (code, customer_id);
                """,
                """
                CREATE INDEX IF NOT EXISTS saga_logs_order_id_idx
                ON saga_logs (order_id);
                """,
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
